#
# 特に説明の無いファイルパスは Profile フォルダーからの相対パスです。
#

[Engine]

# 将棋ソフトの表示名です。 後ろにバージョン番号が付くなどの加工があることがあります。
Name = "Kifuwarakei"

# 将棋ソフトの制作者名です。
Author = "Satoshi TAKAHASHI"

[Resources]

Command = "./Command"
LogDirectory = "../Logs"
